blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/dwalleck/tethys/discussions
    about: Please ask questions and discuss ideas in Discussions
  - name: Documentation
    url: https://github.com/dwalleck/tethys/tree/main/docs
    about: Check our documentation for guides and examples