//HintName: GeneratedEndpoints.g.cs
// <auto-generated/>
using System.Collections.Generic;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Stratify.MinimalEndpoints;

namespace TestApp.Features.HttpMethods
{
    partial class GetMethodEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapGet("/api/method/get", HandleAsync)
                ;
        }
    }
}

namespace TestApp.Features.HttpMethods
{
    partial class PostMethodEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapPost("/api/method/post", HandleAsync)
                ;
        }
    }
}

namespace TestApp.Features.HttpMethods
{
    partial class PutMethodEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapPut("/api/method/put", HandleAsync)
                ;
        }
    }
}

namespace TestApp.Features.HttpMethods
{
    partial class DeleteMethodEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapDelete("/api/method/delete", HandleAsync)
                ;
        }
    }
}

namespace TestApp.Features.HttpMethods
{
    partial class PatchMethodEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapPatch("/api/method/patch", HandleAsync)
                ;
        }
    }
}

namespace TestApp.Features.HttpMethods
{
    partial class HeadMethodEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapMethods("/api/method/head", HandleAsync)
                ;
        }
    }
}

namespace TestApp.Features.HttpMethods
{
    partial class OptionsMethodEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapMethods("/api/method/options", HandleAsync)
                ;
        }
    }
}

