//HintName: GeneratedEndpoints.g.cs
// <auto-generated/>
using System.Collections.Generic;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Stratify.MinimalEndpoints;

namespace TestApp.Features.Nested
{
    partial class NestedEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapGet("/api/nested", HandleAsync)
                ;
        }
    }
}

namespace TestApp.Features.Nested
{
    partial class DeeplyNestedEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapPost("/api/deeply-nested", HandleAsync)
                ;
        }
    }
}

