//HintName: GeneratedEndpoints.g.cs
// <auto-generated/>
using System.Collections.Generic;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Stratify.MinimalEndpoints;

namespace TestApp.Features.Admin
{
    partial class CreateUserEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapPost("/api/admin/users", HandleAsync)
                .RequireAuthorization()
                .RequireAuthorization("AdminPolicy")
                .RequireAuthorization("UserManagementPolicy")
                .RequireAuthorization(policy => policy.RequireRole("Admin", "SuperUser"))
                ;
        }
    }
}

