//HintName: GeneratedEndpoints.g.cs
// <auto-generated/>
using System.Collections.Generic;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Stratify.MinimalEndpoints;

namespace TestApp.Features.Products
{
    partial class GetProductsEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapGet("/api/products", HandleAsync)
                ;
        }
    }
}

