//HintName: GeneratedEndpoints.g.cs
// <auto-generated/>
using System.Collections.Generic;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Stratify.MinimalEndpoints;

namespace TestApp.Features.Test
{
    partial class TestEndpoint : IEndpoint
    {
        public void MapEndpoint(IEndpointRouteBuilder app)
        {
            app.MapGet("/api/test", HandleAsync)
                .WithTags("Tag\"1", "Tag\n2")
                .WithName("Test\"Endpoint")
                .WithSummary("This is a test with \"quotes\" and \nnewlines")
                .WithDescription("Description with special chars: \r\n	\"'\")
                ;
        }
    }
}

